export const FETCH_MOVIES_LIST = 'FETCH_MOVIES_LIST'
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS'
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE'

export const SAVE_DATA_TO_REDUX = 'SAVE_DATA_TO_REDUX'
export const REMOVE_ITEM_FOR_REDUX = 'REMOVE_ITEM_FOR_REDUX'